apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: monitoring-controller
rules:
  - apiGroups: ["monitoring.raisingthefloor.org"]
    resources: ["httpmonitors", "httpmonitors/status"]
    verbs: ["get", "list", "update", "watch"]