apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: monitoring-controller
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["httpmonitors", "httpmonitors/status"]
    verbs: ["get", "list", "update", "watch"]