apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: monitoring-controller
subjects:
  - kind: ServiceAccount
    name: monitoring-controller
    namespace: monitoring
roleRef:
  kind: ClusterRole
  name: monitoring-controller
  apiGroup: rbac.authorization.k8s.io