apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- clusterrole.yaml
- crb.yaml
- crd.yaml
- deployment.yaml
- serviceaccount.yaml
images:
- name: morphicworld/monitoring-controller
  newName: morphicworld/monitoring-controller
  newTag: stable-20200801.2
