apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-controller
  namespace: monitoring
spec:
  template:
    spec:
      containers:
        - name: monitoring-controller
          args:
            - "--set-var"
            - "WEB_URL=https://app.test.morphic.org"
            - "--set-var"
            - "API_URL=https://api.test.morphic.org"
            - "--set-var"
            - "COMMUNITY_URL=https://community.test.morphic.org"
            - "--set-var"
            - "GRAFANA_URL=https://grafana.test.morphic.org"
            - "--set-var"
            - "COUNTLY_URL=https://countly.test.morphic.org"