apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-controller
  namespace: monitoring
spec:
  template:
    spec:
      containers:
        - name: monitoring-controller
          args:
            - "--set-var"
            - "WEB_URL=https://app.msd-test.com"
            - "--set-var"
            - "API_URL=https://api.msd-test.com"
            - "--set-var"
            - "COMMUNITY_URL=https://community.msd-test.com"
            - "--set-var"
            - "GRAFANA_URL=https://grafana.msd-test.com"
            - "--set-var"
            - "COUNTLY_URL=https://countly.msd-test.com"