apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-controller
  namespace: monitoring
spec:
  template:
    spec:
      containers:
        - name: monitoring-controller
          args:
            - "--set-var"
            - "WEB_URL=https://dev-ui.morphiclite-oregondesignservices.org"
            - "--set-var"
            - "API_URL=https://dev-morphic.morphiclite-oregondesignservices.org"
            - "--set-var"
            - "COMMUNITY_URL=https://dev-community.morphiclite-oregondesignservices.org"
            - "--set-var"
            - "GRAFANA_URL=https://dev-grafana.morphiclite-oregondesignservices.org"
            - "--set-var"
            - "COUNTLY_URL=https://dev-countly.morphiclite-oregondesignservices.org"