{
 "title": "Monitoring Controller",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Known Monitoring CRDs",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(monitor_http_crd_details)"
    }
   ]
  },
  {
   "title": "HttpMonitor Info",
   "type": "table",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 0 },
   "targets": [
    { "expr": "monitor_http_crd_details" }
   ]
  },
  {
   "title": "Globally Set Variables",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expr": "monitor_global_var_details" }
   ]
  },
  {
   "title": "HTTP Request Responses",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "monitor_http_response_total", "legendFormat": "{{ url }} - {{ status }}" }
   ]
  }
 ]
}